# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-31 18:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DigestAuthCounter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_nonce', models.CharField(blank=False, max_length=255)),
                ('client_nonce', models.CharField(blank=False, max_length=255)),
                ('client_counter', models.IntegerField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='digestauthcounter',
            unique_together=set([('server_nonce', 'client_nonce')]),
        ),
    ]
